name: pybalmorel
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - pandas>=2.1.4 
  - matplotlib>=3.9.0 
  - geopandas>=1.0.1
  - ipywidgets>=8.1.3
  - ipykernel>=6.29.5
  - pytest=8.3.3
  - pip
  - pip:
    - gamsapi[transfer]>=45.7.0 
    - eel>=0.17.0
    - pybalmorel==0.4.1
